{% set name = "perfplot" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/perfplot-{{ version }}.tar.gz
  sha256: 6ba88aa668e1a7b97ec202ea67e961a855d17dd1aa71e192c7069a641607d3e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core
  run:
    - dufte >=0.2.20
    - importlib-metadata
    - matplotlib
    - numpy
    - python >=3.6
    - rich
    - matplotx >=0.2.8

test:
  imports:
    - perfplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/perfplot
  summary: Performance plots for Python code snippets
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
