{% set name = "perfplot" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/perfplot-{{ version }}.tar.gz
  sha256: 372b73b0bc9f41b0080ba18de01d80c0326689be0765279fd69ee790468a8325

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core
    - matplotlib-base
    - matplotx
    - numpy >=1.20
    - python
    - rich
    - typing_extensions
  run:
    - matplotlib-base
    - matplotx
    - numpy >=1.20
    - python >=3.7
    - rich
    - typing_extensions

test:
  imports:
    - perfplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/perfplot
  summary: Performance plots for Python code snippets
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
